# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f16748309a632a88deaf97c69907ec79885d0a2417a9fa245aad2940e015056ae336ebfa125b97e953556a3a58ffd57ea6bf3c240ada5b06226a61de82c607c

test:
  secret_key_base: 6da27cbe4b87df27e26a9ebdba11932fd4de2b3d8cfa0c3784494ab6d2c3718202874ff853e8f50f57e1ef9dc78deefa033cc71a23ec02487c2911704a9a7644

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
